name: installer-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - devel
  release:
    types:
      - published

jobs:
  deploy-installer:
    name: Deploy Installer
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create folder to upload
        run: |
          mkdir -p ${{ github.workspace }}/installer
          cp install.sh ${{ github.workspace }}/installer
          cp uninstall.sh ${{ github.workspace }}/installer

      - name: Publish (Un-)Installer to IONOS S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws_bucket: kellnr
          endpoint: "https://s3-eu-central-1.ionoscloud.com"
          source_dir: "installer"
          destination_dir: "installer"
